### ISSUE TITLE
Estimate "Genesene" in 2004-corona-grafikartikel/corona-master-public.R

### ISSUE THREAD

**Issue by ghost** [nzzdev/st-methods#8]
https://github.com/nzzdev/st-methods/blob/b8de664599a7b77f1391256a912500545f899f4c/2004-corona-grafikartikel/corona-master-public.R#L130-L137

Hello

First, thank you for your excellent work with COVID-19 visualizations! You are really doing an amazing job.

However, I’m quite sure that your estimation of the recovered cases is flawed in at least two ways. Of course, I may be wrong...

Problem 1: underestimation

A made up example:

For simplicity let’s say we only have two groups of recovered: 80% recover after 10 days, 20% after 40 and no one dies. 

We have 2000 cumulative cases 40 days ago, 4000 10 days ago. With your method (and the fake simple groups), we would estimate that now 2000x0.2+4000x0.8=3200 will have recovered. This is a massive underestimation, because of the 2000 from 40 days ago all should have recovered (since we assume no one dies) and of the 2000 new cases since 40 until 10 days ago at least 80% should have recovered. This means we do now have at least 2000+2000x0.8=3600. This is still wrong, but closer to the value we expect.

Problem 2: overestimation

While your method leads to underestimation while the cumulative case number is growing, it actually leads to an overestimation if they are constant for a long time. This is because you do not account for the deaths (at least here). Not all infected will survive but your percentages sum up to one. So if the case numbers are constant for a long time (no newly infected), your method leads to (cumulative cases)<(active+recovered+deaths). In another r-file you take into account the deaths at the lag time, but this does not solve the problem, since not all that will have died until now had been dead then.

Possible solution:

One possible solution would be to look at the cases individually. You give every new case a recovery time and loop over the whole period until now to see how many will have recovered. You also need to take care of those that die, which you have to distribute somehow at incidence of death. If you are interested, I could send you some code. But no warranty from my side for it’s correctness and there may be way better solutions!

**Comment by nthelitz** [comment]
Thank you for your feedback! I am not sure the issues you highlighted are valid:

- Underestimation: 2000x0.2+4000x0.8 is 3600, not 3200 - i do not follow how 3600 is still too low, since we assume that 20% of 2000 are still not recovered after 10 days.
- Overestimation: We deduct deceased cases on line 122, the naming conventions is suboptimal https://github.com/nzzdev/st-methods/blob/b8de664599a7b77f1391256a912500545f899f4c/2004-corona-grafikartikel/corona-master-public.R#L122-L123

**Comment by ghost** [comment]
Thanks for the reply. Haha, I basically proofed myself wrong with this bad calculation. Sorry about that.
I'm definitely wrong with this one!

I still suspect that the overestimation point may hold because you deduct only those that were dead at lag time. Say confirmed cases stay constant from t-40 until now at 4000, but some have died. Say 1000 have died from t-40 until t-10, further 500 died from t-10 until now (this is intentionally way too much, just to stress the point).

So we have alive confirmed cases (recovered or still infected):
t-40: 4000
t-10: 3000
now: 2500

Now we have 4000x0.2+3000x0.8=3200 that will have recovered according to your method (hope I got this right this time:)). That is 700 more than alive cases now. (Of course the problem is rather marginal in real live because not as many die).

I really hope I have this one wrong too. Anyway, thank your for taking requests seriously!

Edit: I calculated it with both methods, yours and ours. The difference is rather small, at most you get around 400 recovered people more in mid april (see the pictures).

Edit 2: I initially asked because we searched for a method to calculate this. We do have one now that works fine, so no need to bother. We can just close the issue.

![Differenz_Genesene](https://user-images.githubusercontent.com/55285519/84417975-c0ac5980-ac16-11ea-8e71-6a62e1208c6d.png)
![Vergleich_Genesene](https://user-images.githubusercontent.com/55285519/84417987-c43fe080-ac16-11ea-9592-d898cc0516b5.png)
